tint_compNamespace = [] call CBA_fnc_createNamespace;

// #include "compositions\beesting_CUP.sqf"
// #include "compositions\city.sqf"
// #include "compositions\jono_deserted.sqf"
// #include "compositions\jono_fortified.sqf"
#include "compositions\jono_houses.sqf"
#include "compositions\jono_military.sqf"
#include "compositions\lived_in.sqf"
// #include "compositions\livonia.sqf"
#include "compositions\livonia_nonmodern.sqf"
#include "compositions\orange_prewar.sqf"
// #include "compositions\orange_war.sqf"
// #include "compositions\orange_postwar.sqf"
// #include "compositions\ravage_clean.sqf"
// #include "compositions\ravage_dirty.sqf"
#include "compositions\vn_huts.sqf"
// #include "compositions\vn_huts_vc.sqf"
// #include "compositions\weferlingen_cup.sqf"
#include "compositions\weferlingen_lived_in.sqf"
// #include "compositions\WF_houses_cup.sqf"
//#include "compositions\WS_lived_in_Cup_alt.sqf"
//#include "compositions\WS_lived_in_Cup.sqf"
